name: Frontend Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/m324-frontend:latest
        build-args: |
          VITE_API_URL=${{ secrets.VITE_API_URL }}

    # Optional: Frontend dist zusätzlich als Artifact hochladen (wie vorher)
    - name: Upload Dist Folder
      uses: actions/upload-artifact@v4
      with:
        name: frontend-dist
        path: ./frontend/dist
